/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajeroonline;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.util.Date;
import javax.swing.JComponent;

/**
 *
 * @author User
 */
public class Plata extends javax.swing.JFrame {

    DefaultTableModel df = new DefaultTableModel();

    public Plata() {
        initComponents();
        setLocationRelativeTo(null);

        String[] id = new String[]{"Usuario transferido", "Total", "Fecha"};
        df.setColumnIdentifiers(id);
        trans_tabla.setModel(df);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        button_transferir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_usert = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ingreso = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trans_tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        txt_retiro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_cantida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(733, 322));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        button_transferir.setText("Transferir");
        button_transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_transferirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(12, 12, 178));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hacia:");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingreso:");

        trans_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Usuario transferido", "Total", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trans_tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        trans_tabla.setEnabled(false);
        jScrollPane1.setViewportView(trans_tabla);

        jButton2.setText("Retirar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Retiro:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Transferencias");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Historial de Transferencias");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_cantida.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        label_cantida.setForeground(new java.awt.Color(255, 255, 255));
        label_cantida.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Movimientos");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(label_cantida))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel5)
                            .addComponent(txt_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txt_usert, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(button_transferir)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(txt_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton1)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addComponent(txt_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton2)
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(label_cantida)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(txt_usert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7)
                        .addGap(0, 0, 0)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(button_transferir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ingreso = txt_ingreso.getText().trim();
        if (ingreso.matches("\\d+(\\.\\d+)?")) {

            int opcion = JOptionPane.showConfirmDialog(null, "Desea ingresar " + ingreso + "?", "", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                Connection cn = c.getConnection();
                prepareUser(cn);
                double aux = Double.parseDouble(ingreso) + user_money;

                try {
                    PreparedStatement pst = cn.prepareStatement("update user_data set money = ? where user_user = ?");
                    pst.setDouble(1, aux);
                    pst.setString(2, user);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Adicion exitosa");
                    setLabel(cn);
                    txt_ingreso.setText("");
                    pst.close();
                    cn.close();
                } catch (Exception e) {
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Caracteres Incorrectos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String retiro = txt_retiro.getText().trim();
        if (retiro.matches("\\d+(\\.\\d+)?")) {

            int opcion = JOptionPane.showConfirmDialog(null, "Desea retirar " + retiro + "?", "", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                Connection cn = c.getConnection();
                prepareUser(cn);
                double aux = user_money - Double.parseDouble(retiro);
                if (aux < 0) {
                    JOptionPane.showMessageDialog(null, "No se puede retirar!");
                } else {
                    try {
                        PreparedStatement pst = cn.prepareStatement("update user_data set money = ? where user_user = ?");
                        pst.setDouble(1, aux);
                        pst.setString(2, user);
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Extraccion exitosa");
                        setLabel(cn);
                        txt_retiro.setText("");
                        pst.close();
                        cn.close();
                    } catch (Exception e) {
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Caracteres Incorrectos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void button_transferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_transferirActionPerformed
        String total = txt_total.getText().trim();
        if (total.matches("\\d+(\\.\\d+)?")) {
            if (txt_usert.getText().trim().equals(user)) {
                JOptionPane.showMessageDialog(null, "No te puedes transferir a ti mismo");
            } else {
                int opcion = JOptionPane.showConfirmDialog(null, "Desea transferir " + total + "? ", "", JOptionPane.YES_NO_OPTION);
                if (opcion == JOptionPane.YES_OPTION) {
                    Connection cn = c.getConnection();
                    prepareUser(cn);
                    double aux = user_money - Double.parseDouble(total);
                    if (aux < 0) {
                        JOptionPane.showMessageDialog(null, "Fondos insuficientes");
                    } else {
                        String usert = txt_usert.getText().trim();
                        try {
                            PreparedStatement pst = cn.prepareStatement("select * from user_data where user_user = ?");
                            pst.setString(1, usert);
                            ResultSet rs = pst.executeQuery();
                            if (rs.next()) {
                                PreparedStatement ps = cn.prepareStatement("update user_data set money = money + ? where user_user = ?");
                                ps.setString(1, total);
                                ps.setString(2, usert);
                                ps.executeUpdate();

                                PreparedStatement p = cn.prepareStatement("update user_data set money = money - ? where user_user = ?");
                                p.setString(1, total);
                                p.setString(2, user);
                                p.executeUpdate();
                                setTransfer(cn, user, usert, total);
                                setLabel(cn);
                                setTable(cn);

                                JOptionPane.showMessageDialog(null, "Transaccion enviada");
                                txt_usert.setText("");
                                txt_total.setText("");
                                ps.close();
                                p.close();
                            }
                            pst.close();
                            rs.close();
                            cn.close();
                        } catch (Exception e) {
                        }
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Caracteres Incorrectos");
        }
    }//GEN-LAST:event_button_transferirActionPerformed
    private void setLabel(Connection cn) {
        prepareUser(cn);
        label_cantida.setText(String.valueOf(String.format("%.2f", user_money)));
    }

    public void getUser(String user) {
        this.user = user;
        Connection cn = c.getConnection();
        prepareUser(cn);
        setLabel(cn);
        setTable(cn);
        try {
            cn.close();
        } catch (Exception e) {
        }
    }

    private void setTransfer(Connection cn, String user_origin, String user_trans, String money) {
        try {
            PreparedStatement pst = cn.prepareStatement("Insert into transfer_data values(?,?,?,?,?,?)");
            pst.setString(1, user_origin);
            pst.setString(2, user_trans);
            pst.setDouble(3, Double.parseDouble(money));
            pst.setString(4, String.valueOf(new Date()));
            pst.setString(5, "0");
            pst.setInt(6, user_id);
            pst.executeUpdate();
            pst.close();
        } catch (Exception e) {
        }
    }

    private void setTable(Connection cn) {
        try {
            PreparedStatement pst = cn.prepareStatement("select * from transfer_data where user_id = ?");
            DefaultTableModel model = (DefaultTableModel) trans_tabla.getModel();
            model.setRowCount(0);
            trans_tabla.setFillsViewportHeight(true);
            ((JComponent) trans_tabla.getParent()).setBackground(Color.lightGray);
            pst.setInt(1, user_id);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                do {
                    String origin = rs.getString("user_origin");
                    String reciver = rs.getString("user_reciver");
                    String date = rs.getString("date");
                    double trans = rs.getDouble("reciver_money");

                    if (origin.equals(user)) {

                        model.addRow(new Object[]{reciver, "-" + trans, date});
                    } else if (reciver.equals(user)) {

                        model.addRow(new Object[]{origin, trans, date});
                    }
                } while (rs.next());
            }
            rs.close();
            pst.close();
        } catch (Exception e) {
            System.out.println("Error" + e);
        }
    }

    private void prepareUser(Connection cn) {
        try {
            PreparedStatement pst = cn.prepareStatement("select * from user_data where user_user = ?");
            pst.setString(1, user);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                user_money = rs.getDouble("money");
                user_id = rs.getInt("id");
                label_cantida.setText(String.valueOf(String.format("%.2f", user_money)));
            } else {
                System.out.println("no existe");
            }
            pst.close();
            rs.close();
        } catch (Exception e) {
            System.out.println("erroe" + e);
        }
    }

    private String user;
    private double user_money;
    private int user_id;
    private Conection c = new Conection();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_transferir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_cantida;
    private javax.swing.JTable trans_tabla;
    private javax.swing.JTextField txt_ingreso;
    private javax.swing.JTextField txt_retiro;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_usert;
    // End of variables declaration//GEN-END:variables
}
