/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajeroonline;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form usuario
     */
    public Usuario() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        txt_rpass = new javax.swing.JPasswordField();
        txt_pass = new javax.swing.JPasswordField();
        txt_mail = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tagg = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        cambiar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        exitazo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(697, 225));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Desea cambiar el usuario?");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Cuando usted cambia de usuario, se\nmodifica la cuenta y el acceso a la \nmisma, a partir del cambio debera poner \nla misma en cada aspecto. En base a eso, \nse estaran contactando para cambiarla,\nluego de que toque el boton");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea1.setFocusable(false);
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordListener passwordListener = new PasswordListener(txt_pass, txt_rpass, tagg, modificar);
        txt_rpass.getDocument().addDocumentListener(passwordListener);
        jPanel1.add(txt_rpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 90, 215, -1));

        txt_pass.getDocument().addDocumentListener(passwordListener);
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 62, 215, -1));
        jPanel1.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 34, 215, -1));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 6, 215, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 152, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 9, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mail: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 37, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 65, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Repetir Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, -1, -1));

        tagg.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        tagg.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tagg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 220, 16));

        cambiar.setText("Pedir cambio");
        cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(name))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(modificar)
                .addGap(171, 171, 171)
                .addComponent(cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(name)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificar)
                    .addComponent(cambiar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        String nombre = txt_nombre.getText().trim();
        String mail = txt_mail.getText().trim();
        if (txt_pass.getPassword().length == 0 && nombre.equals("") && mail.equals("")) {
            JOptionPane.showMessageDialog(null, "No hay cambios detectados");
            return;
        }
        Connection cn = c.getConnection();
        prepareUser(cn);
        try {
            PreparedStatement pst = cn.prepareStatement("update user_data set user_name = ?, user_mail = ?, user_pass = ? where user_user = ?");
            if (nombre.equals("")) {
                pst.setString(1, user_name);
            } else {
                pst.setString(1, nombre);
            }
            if (mail.equals("")) {
                pst.setString(2, user_mail);
            } else {
                pst.setString(2, mail);
            }
            if (txt_pass.getPassword().length == 0) {
                pst.setString(3, user_pass);
            } else {
                pst.setString(3, new String(txt_pass.getPassword()));
            }
            pst.setString(4, user);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Modificacion exitosa");
            exitazo.setText("Modificacion exitosa");
            txt_nombre.setText("");
            txt_mail.setText("");
            txt_pass.setText("");
            txt_rpass.setText("");
            pst.close();
            cn.close();
        } catch (Exception e) {
            System.out.println("Error AB: " + e);
            JOptionPane.showMessageDialog(null, "No hay conexion");
        }

    }//GEN-LAST:event_modificarActionPerformed

    private void cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarActionPerformed
        Connection cn = c.getConnection();
        try {
            PreparedStatement pst = cn.prepareStatement("insert into ayuda_data values(?,?,?,?)");
            pst.setInt(1, id);
            pst.setString(2, "Cambiar User");
            pst.setInt(3, 0);
            pst.setString(4, "Incompleto");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ticket generado");
            cn.close();
            pst.close();
        } catch (Exception e) {
            System.out.println("Error en cambio de user: " + e);
        }
    }//GEN-LAST:event_cambiarActionPerformed
    public void getUser(String user) {
        this.user = user;
        Connection cn = c.getConnection();
        prepareUser(cn);
        try {
            cn.close();
        } catch (Exception e) {
        }
        
    }
    
    private void prepareUser(Connection cn) {
        try {
            PreparedStatement pst = cn.prepareStatement("select * from user_data where user_user = ?");
            pst.setString(1, user);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                id = rs.getInt("ID");
                user_name = rs.getString("user_name");
                user_mail = rs.getString("user_mail");
                user_pass = rs.getString("user_pass");
            }
            pst.close();
            rs.close();
        } catch (Exception e) {
            System.out.println("Erorr en prepareUserAA: " + e);
        }
    }
    private int id;
    private String user;
    private String user_name, user_mail, user_pass;
    private Conection c = new Conection();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiar;
    private javax.swing.JLabel exitazo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton modificar;
    private javax.swing.JLabel name;
    private javax.swing.JLabel tagg;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JPasswordField txt_rpass;
    // End of variables declaration//GEN-END:variables
}
